name: Kowalski

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  test_kowalski:
    name: Test Kowalski
    runs-on: ubuntu-latest

    steps:
      - name: Use Kowalski
        id: kowalski
        uses: liquidibrium/kowalski-github-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: 'gpt-4'
